# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: mattcongel@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "http://mattcongel.info" # the base hostname & protocol for your site
twitter_username: mattcongel
github_username:  homeofmatt

exclude:
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - Procfile

assets:
    digest: true
    sources:
      - "_assets/styles"
      - "_vendor/materialize-src/sass"
      - "_vendor/materialize-src/js/bin"

# Build settings
markdown: kramdown
